ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.kanbanvision.httpapi.MainKt.module ]
    }
}

database {
    url      = "jdbc:postgresql://localhost:5432/kanbanvision"
    url      = ${?DATABASE_URL}
    driver   = "org.postgresql.Driver"
    user     = "kanban"
    user     = ${?DATABASE_USER}
    password = "kanban"
    password = ${?DATABASE_PASSWORD}
    poolSize = 10
}
